---
- name: Restart ssh
  action: service name=ssh state=restarted

- name: update timezone
  command: dpkg-reconfigure --frontend noninteractive tzdata

- name: restart nginx
  service: name=nginx state=restarted enabled=yes

- name: reload nginx
  service: name=nginx state=reloaded
